on:
  pull_request:
    types: [closed]
    branches: [master]
  push:
    branches: [master]
jobs:
  push-to-gcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Activate service account
        run: gcloud auth activate-service-account --key-file=<(echo '${{ secrets.YOUR_SECRET_NAME }}')

      - name: Sync files to GCS
        run: gsutil -m rsync -r -d ./testproject gs://to_archive/Phanindra/github_action_test
