on:
  pull_request:
    types: [closed]
    branches: [master]
  push:
    branches: [master]
jobs:
  push-to-gcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/authv@0.4.0
        with:
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          project_id: prj-ich-dwh-workspace-dev-fe16

      - name: Sync files to GCS
        run: gsutil -m rsync -r -d ./local gs://data-sources-development/github_test
